### ISSUE TITLE
Missing HelmRepository Instructions

### ISSUE THREAD

**Issue by danehans** [livewyer-ops/poc-servicemesh2024#4]
I am trying to reproduce the tests in this guide. The guide states:

>The following Flux `HelmRelease` template will be used to create clusters in LWDE. Depending on service mesh requirements, some values can be changed. Any changes will be highlighted in the `Cluster Configuration` subsection of the Product section.
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: <cluster-name>
  namespace: flux-system
spec:
  chart:
    spec:
      chart: capi-aws-eks-cluster
      version: 0.1.5
      sourceRef:
        kind: HelmRepository
        name: lw-helm-charts-registry
...
```

The HelmRelease references a HelmRepository that does not exist in this repo. Can you provide details for the referenced HelmRepository?
